# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.1                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.21-school.ru>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/03 22:27:45 by cbach             #+#    #+#              #
#    Updated: 2020/11/03 22:33:06 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =	cub3d
FLAGS = -Wall -Wextra -Werror

HEADERS =								\
		get_next_line/get_next_line.h	\
		cub3d.h

GNL_SRCS = get_next_line/*.c

PARSER_SRCS = parser/*.c

RAYCASTING_SRCS = raycasting/*.c

MAIN_SRCS = *.c



SRC =						\
		

BONUS =						\
		ft_lstnew.c			\
		ft_lstadd_front.c	\
		ft_lstsize.c		\
		ft_lstlast.c		\
		ft_lstadd_back.c	\
		ft_lstdelone.c		\
		ft_lstclear.c		\
		ft_lstiter.c		\
		ft_lstmap.c			\

OBJ = $(patsubst %.c, %.o, $(SRC))
OBJ_BONUS = $(patsubst %.c, %.o, $(BONUS))

ifdef BONUS_FILES
OBJ_FILES = $(OBJ_BONUS)
else
OBJ_FILES = $(OBJ)
endif

.PHONY: all bonus clean fclean re so

all: $(NAME)
	rm -f .depend

$(NAME): $(OBJ_FILES)
	ar -rcs $(NAME) $?

bonus:
	$(MAKE) BONUS_FILES=1 all

.depend: $(SRC) $(BONUS)
	rm -f .depend
	gcc $(FLAGS) -MM $^ > .depend;

-include .depend

%.o:
	gcc $(FLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(OBJ_BONUS) .depend

fclean: clean
	rm -f $(NAME)
	rm -f $(NAME_SO)

re: fclean all

so: $(NAME_SO)

$(NAME_SO):
	gcc -c -fPIC *.c
	gcc -shared -o libft.so *.o
